
server:
  port: 8761

eureka:
  server:
    eviction-interval-timer-in-ms: 1000
  instance:
    prefer-ip-address: false
  client:
    register-with-eureka: false
    fetch-registry: false

spring:
  application:
    name: eureka-service